config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new()
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end

  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Create a New Bookmark</h1>
<h3>Add a movie to your <%= @list.name %> list</h3>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
  <%= f.association :movie %>
  <%= f.submit "Add movie" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMovieList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists index</h1>
<%= cl_image_tag("dzjf3eojigvzocqjjnan",
      width: 400, height: 300, crop: :fill) %>
<% @lists.each do |list| %>
  <h2> <%= link_to list.name, list_path(list) %></h2>
<% end %>
<%= link_to 'Add a New List', new_list_path %>

app/views/lists/new.html.erb
<h1>Create a New List</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>

  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %> List</h1>
<h3><%= "You haven't saved any movies yet!" if @list.movies.empty? %></h3>
<% @list.bookmarks.each do |bookmark| %>
  <h2><%= bookmark.movie.title %></h2>
  <p><%= bookmark.movie.overview %></p>
  <%= link_to "Delete",
                    bookmark_path(bookmark),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %>
  <hr>
<% end %>
<%= link_to 'Back to the List', lists_path %> |
<%= link_to 'Add a movie', new_list_bookmark_path(@list) %> |